# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa0a03e6dfa1b31ad5b4463ea9f0913c3fd99403cb80a0250945f44f59a77bcce578c2c92accb90a78badf29b05737a2c401352e994bf30cc7ed0b9ed2ab651d

test:
  secret_key_base: 8d80810c0404c44c3da353e801b5376e63137e15898a718640201226db31b1002e023b71d9011f61fee1d91b3deff176ec240c633d11be7b3aa9de1ef4cce0c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
